<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Notifications;
use App\Events\NotificationCreated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NotificationsController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $perPage = (int) $request->query('per_page', 20);

        $query = Notifications::where('user_id', $user->id)->orderBy('created_at', 'desc');

        $paginated = $query->paginate($perPage);

        return response()->json($paginated);
    }

    public function unreadCount(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $count = Notifications::where('user_id', $user->id)->where('is_read', false)->count();

        return response()->json(['count' => $count]);
    }

    public function markRead(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $ids = $request->input('ids', []);
        if (!is_array($ids) || empty($ids)) {
            return response()->json(['message' => 'No ids provided'], 400);
        }

        $updated = Notifications::where('user_id', $user->id)
            ->whereIn('notification_id', $ids)
            ->update(['is_read' => true, 'read_at' => now()]);

        return response()->json(['updated' => $updated]);
    }

    public function markAllRead(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $updated = Notifications::where('user_id', $user->id)
            ->where('is_read', false)
            ->update(['is_read' => true, 'read_at' => now()]);

        return response()->json(['updated' => $updated]);
    }

    /**
     * Dev helper: create a test notification for the current user and broadcast it.
     * POST /api/notifications/simulate
     */
    public function simulate(Request $request)
    {
        $user = $request->user();
        if (! $user) {
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $title = $request->input('title', 'Test Notification');
        $message = $request->input('message', 'Generated by simulate endpoint');
        $type = $request->input('type', 'test');

        $notif = Notifications::create([
            'user_id' => $user->id,
            'type' => $type,
            'title' => $title,
            'message' => $message,
            'is_read' => false,
        ]);

        // broadcast the event so frontend Echo receives it
        event(new NotificationCreated($notif));

        return response()->json(['ok' => true, 'notification' => $notif]);
    }
}
